version: "3"
services:
  n8n:
    build: .
    image: jspiers/n8n-joplin
    # Define these environment variables in a .env file
    # environment:
    #   - POP3_USER
    #   - POP3_PW
    #   - POP3_HOST
    #   - POP3_PORT
    #   - GETMAIL_OPTS
    #   - DEFAULT_TITLE_PREFIX
    #   - DEFAULT_NOTEBOOK
    #   - AUTO_CREATE_NOTEBOOK
    volumes:
      - ./joplin-config.json:/secrets/joplin-config.json
      - type: volume
        source: joplin-data
        target: /home/node/.config/joplin
      - ./.n8n:/home/node/.n8n
    ports:
      - "5678:5678"
    # command: ["joplin config --import-file /secret/joplin-config.json && ./fetch-joplin-mails.sh"]
volumes:
  joplin-data:
  # mail-data:
  # fetch-joplin-mails-log:
