version: "3"
services:
  joplin:
    build: .
    image: jspiers/joplin-client
    volumes:
      - ./joplin-config.json:/secrets/joplin-config.json
      - type: volume
        source: joplin-data
        target: /home/node/.config/joplin
    ports:
      - "41187:41187"

volumes:
  joplin-data:
