version: "3"
services:
  n8n:
    image: n8nio/n8n:0.107.0
    ports:
      - "5678:5678"
    volumes:
      - type: volume
        source: n8n-data
        target: /home/node/.n8n
  joplin:
    image: jspiers/headless-joplin:1.6.4-node-14.15.5
    volumes:
      - ./joplin-config.json:/secrets/joplin-config.json
      - type: volume
        source: joplin-data
        target: /home/node/.config/joplin
    expose:
      - 80
volumes:
  joplin-data:
  n8n-data:
