version: "3"
services:
  n8n:
    build: .
    image: jspiers/n8n-joplin
    volumes:
      - ./joplin-config.json:/secrets/joplin-config.json
      - type: volume
        source: joplin-data
        target: /home/node/.config/joplin
      - ./.n8n:/home/node/.n8n
    ports:
      - "5678:5678"
volumes:
  joplin-data:
